<?php include "db.php";
				
				$sql2v= "SELECT * FROM payment 
				left join accounts on(payment.referanceid=accounts.id)  
				WHERE payment.pfor=8 and payment.ptyid='".$_REQUEST['id']."' AND amount>0";
			    $result2v = $conn->query($sql2v);
			    
			    $sql2= "SELECT * FROM payment 
				left join accounts on(payment.referanceid=accounts.id) 
				WHERE payment.pfor=8 and payment.ptyid='".$_REQUEST['id']."'";
			    $result2 = $conn->query($sql2);
			  
				
				
				 $sql= "SELECT * FROM transaction 
                LEFT JOIN accounts On (accounts.id=transaction.bank_id)
                WHERE transaction.id='".$_REQUEST['id']."'";
                $result = $conn->query($sql);
				
				$sql= "SELECT *,accounts.name as bname,transaction.create_date as tdate FROM transaction 
				LEFT JOIN accounts On (accounts.id=transaction.bank_id)
				WHERE transaction.id='".$_REQUEST['id']."'";
			    $result = $conn->query($sql);
				$row = $result->fetch_assoc();
				?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="https://www.w3.org/1999/xhtml">
<head>
<meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
<title>Transaction</title>
<link rel='stylesheet' type='text/css' href='css/style.css' />
<link rel='stylesheet' type='text/css' href='css/print.css' media="print" />
</head>

<body style="background-color: aliceblue;">
<div id="page-wrap" style="background-color:#FFFFFF;">

 <?php include('header.php');?>Petty Cash
</textarea>
<div style="clear:both"></div>
<div id="customer">
    <div id="customer-title" style="margin-left: 50px;margin-top:5px;width:300px;">
    <span > Voucher # : </span>
    <span style="color:#999;"><?php echo $row['vno']; ?></span>
    <hr/>
    <span > Dated : </span>
    <span style="color:#999;"><?php echo $row['tdate']; ?></span>
    <hr/>
  </div>
  <div id="meta" style="margin-left: 20px;"> <span > Amount :</span>
  <span style="color:#999;"><?php echo $row['amount']; ?></span>
    <hr/>
    <span >Amount In Words :</span>
    <span style="color:#999;"><?php echo ucwords(Word($row['amount'])) ?></span>
    <hr/>
  </div>
<?php   $row2v = $result2v->fetch_assoc();
?>
  <div style="clear:both"></div>
  <table id="items">
    <tr>
      <th>S No.</th>
      <th>AccountTitle</th>
      <th>Naration</th>
      <th>Debit</th>
      <th>Credit</th>
    </tr>
    
<?php $td=0;$tc=0;$i=0; while($row2 = $result2->fetch_assoc()){ $i=$i+1; ?>    
    <tr>
      <td><?php echo $i; ?></td>
      <td><?php echo $row2['name'];?></td>
      <td><?php echo $row2['remarks'];?></td>
      <td><?php echo number_format($row2['amount'],2)?></td>
      <td><?php echo number_format($row2['amount1'],2)?></td>
     <?php $td=$td+$row2['amount'];$tc=$tc+$row2['amount1'];?>
    </tr>
   <?php }?>
    <tr>
      <td></td>
      <td></td>
      <td></td>
      <td class="total-value" > Total : <?php echo number_format($td,2);?></td>
        <td class="total-value"   > Total : <?php echo number_format($tc,2);?></td>
    </tr>
  </table>
  <?php
   $sql2= "SELECT * FROM transaction 
				LEFT JOIN employee ON (transaction.user_id=employee.id)
				WHERE transaction.id='".$_REQUEST['id']."'";
			    $result2 = $conn->query($sql2);
				$row2 = $result2->fetch_assoc();
  ?>
  <div style="clear:both"></div>
  <div style="margin-top: 1%;">
    <p style="font-size: 12px;">Generated By: <?php echo $row2['name']; ?> &nbsp;&nbsp;&nbsp;&nbsp; Print Date: <?php echo date('d-M-y'); ?></br>
    <p style="margin-top: 3%;">Prepared by:______________________________________ Checked By:_____________________________________</p></br>
    <p style="margin-top: 3%;">Approved By:______________________________________</p>
</div>
</div>
<hr style="margin:5px 0px;" />
</div>

</body>
</html>

<?php
function Word($num){
    			$num    = ( string ) ( ( int ) $num );
				if( ( int ) ( $num ) && ctype_digit( $num ) ){
					 $words  = array( );
					 $num    = str_replace( array( ',' , ' ' ) , '' , trim( $num ) );
					 $list1  = array('','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen');
					 $list2  = array('','ten','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety','hundred');
					 $list3  = array('','thousand','million','billion','trillion','quadrillion','quintillion','sextillion','septillion','octillion','nonillion','decillion','undecillion','duodecillion','tredecillion','quattuordecillion','quindecillion','sexdecillion','septendecillion','octodecillion','novemdecillion','vigintillion');	
					 $num_length = strlen( $num );
					 $levels = ( int ) ( ( $num_length + 2 ) / 3 );
					 $max_length = $levels * 3;
					 $num    = substr( '00'.$num , -$max_length );
					 $num_levels = str_split( $num , 3 );
					 foreach( $num_levels as $num_part ){
						 $levels--;
            			 $hundreds   = ( int ) ( $num_part / 100 );
            			 $hundreds   = ( $hundreds ? ' ' . $list1[$hundreds] . ' hundred' . ( $hundreds == 1 ? '' : 's' ) . ' ' : '' );
            			 $tens= ( int ) ( $num_part % 100 );
            		     $singles= '';
            				if( $tens < 20 ){
                				$tens   = ( $tens ? ' ' . $list1[$tens] . ' ' : '' );}
            				else{ 
                				$tens   = ( int ) ( $tens / 10 );
                				$tens   = ' ' . $list2[$tens] . ' ';
                				$singles    = ( int ) ( $num_part % 10 );
                				$singles    = ' ' . $list1[$singles] . ' ';}
            					$words[]    = $hundreds . $tens . $singles . ( ( $levels && ( int ) ( $num_part ) ) ? ' ' . $list3[$levels] . ' ' : '' );}
        						$commas = count( $words );
        				if( $commas > 1 ){
            				$commas = $commas - 1;}
        				$words  = implode( ' ' , $words );
   						return $words.' Only';}else if( ! ( ( int ) $num ) ){return 'Zero';}

    				return '';}
?>